### ISSUE TITLE
Product Details

### ISSUE THREAD

**Issue by Octowl** [Octowl/cove#15]
When the user clicks on a product from the product list they should be taken to a product detail page

**Comment by jennazenk** [comment]
![img_0233](https://cloud.githubusercontent.com/assets/17808182/15838957/c5f85c2c-2c0e-11e6-8217-8976d7311b29.JPG)

**Comment by jennazenk** [comment]
![img_0234](https://cloud.githubusercontent.com/assets/17808182/15838980/db054486-2c0e-11e6-9e76-4fc7c98ca145.JPG)
